### ISSUE TITLE
maven could not find artifact jar problem

### ISSUE THREAD

**Issue by haotianxing** [tetherless-world/linkipedia#1]
Hi Jim,

I was trying to run the system and have a error in the process of using the command (mvn package install). I'm really appreciate it if you can give me some advice and some pieces of guidance.

<img width="1325" alt="img0" src="https://cloud.githubusercontent.com/assets/17220562/13958653/ddf08c50-f08b-11e5-95f4-c5dfa8c2d761.png">

Best regards,
Haotian

**Comment by jimmccusker** [comment]
I needed to update the pom.xml to use the right release for the D1 jars. Thanks for noticing.
