### ISSUE TITLE
dataone-ontologies.sh had trouble resolving most of the URI's

### ISSUE THREAD

**Issue by chastk** [tetherless-world/linkipedia#2]
Output from the script:

rapper: Parsing URI https://raw.githubusercontent.com/DataONEorg/sem-prov-ontologies/master/observation/d1-ECSO.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Error -  - XML HTTP error: Unknown IO error - Not a valid HTTP URI
rapper: Failed to parse URI https://raw.githubusercontent.com/DataONEorg/sem-prov-ontologies/master/observation/d1-ECSO.owl rdfxml content
rapper: Parsing returned 0 triples
rapper: Parsing URI http://ecoinformatics.org/oboe/oboe.1.1/oboe.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Parsing returned 8 triples
rapper: Parsing URI http://ecoinformatics.org/oboe/oboe.1.1/oboe-core.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Parsing returned 522 triples
rapper: Parsing URI http://ecoinformatics.org/oboe/oboe.1.1/oboe-characteristics.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Parsing returned 151 triples
rapper: Parsing URI http://ecoinformatics.org/oboe/oboe.1.1/oboe-standards.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Parsing returned 4323 triples
rapper: Parsing URI http://purl.dataone.org/odo/d1-generated-ECSO.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Error -  - XML HTTP error: Unknown IO error - Not a valid HTTP URI
rapper: Failed to parse URI http://purl.dataone.org/odo/d1-generated-ECSO.owl rdfxml content
rapper: Parsing returned 0 triples
rapper: Parsing URI http://purl.dataone.org/obo/ENVO_import.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Error -  - XML HTTP error: Unknown IO error - Not a valid HTTP URI
rapper: Failed to parse URI http://purl.dataone.org/obo/ENVO_import.owl rdfxml content
rapper: Parsing returned 0 triples
rapper: Parsing URI http://purl.dataone.org/obo/PATO_import.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Error -  - XML HTTP error: Unknown IO error - Not a valid HTTP URI
rapper: Failed to parse URI http://purl.dataone.org/obo/PATO_import.owl rdfxml content
rapper: Parsing returned 0 triples
rapper: Parsing URI http://purl.dataone.org/obo/UO_import.owl with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Error -  - XML HTTP error: Unknown IO error - Not a valid HTTP URI
rapper: Failed to parse URI http://purl.dataone.org/obo/UO_import.owl rdfxml content
rapper: Parsing returned 0 triples
rapper: Parsing URI http://www.w3.org/TR/skos-reference/skos-owl1-dl.rdf with parser rdfxml
rapper: Serializing with serializer ntriples
rapper: Parsing returned 238 triples

All the HTTP URI's were valid and up and running - I was able to download the ontologies manually and use rapper to convert them to N-triples after that.

**Comment by jimmccusker** [comment]
Please see the new Python downloader for DataONE.
